### ISSUE TITLE
go_on_date vs. go_on_a_date

### ISSUE THREAD

**Issue by garettarrowood** [learn-co-curriculum/object-relations-intro#3]
The code that you uncomment and run after the first "Code Along" section calls the "go_on_date" method. But in the examples in the lab, the method is defined as "go_on_a_date". This throughs an undefined method error when you run the final. So just change all the mentions of the method so they are the same.

Nice work on all these new labs!

**Comment by AnnJohn** [comment]
Fixed. Closing issue
